version: '3.4'

services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: data
      POSTGRES_USER: root

  adminer:
    image: adminer
    container_name: "adminer"
    restart: unless-stopped
    ports:
      - 8082:8080

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8883:8883
