quarkus:
  application:
    name: airq-measurement-processor
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://10.1.1.50:5432/warehouse
    reactive:
      url: postgresql://10.1.1.50:5432/warehouse
  vertx:
    prefer-native-transport: true

mp:
  messaging:
    incoming:
      airq-events:
        connector: smallrye-mqtt
        topic: /airq/sensors
        host: vmq
        port: 1883
        broadcast: true
        timeout-on-connect: 5


#"%dev":
#  quarkus:
#    datasource:
#      url: vertx-reactive:postgresql://localhost:5432/data
#      username: root
#      password: example

