quarkus:
  application:
    name: airq-measurement-processor
  datasource:
    url: vertx-reactive:postgresql://db:5432/warehouse
    username: warehouse_admin
    password: NZGJbSCnxa9VP675Mdbkm9eRP5By4f9E

mp:
  messaging:
    incoming:
      airq-events:
        connector: smallrye-mqtt
        topic: /airq/sensors
        host: vmq
        port: 1883
        user: AIRQMP
        password: U492WN7GQrEGRyzrRfR9xsrKsVu2TfGB
        broadcast: true
        timeout: 1000

"%dev":
  quarkus:
    datasource:
      url: vertx-reactive:postgresql://localhost:5432/data
      username: root
      password: example
  mp:
    messaging:
      incoming:
        airq-events:
          host: localhost
          user:
          password:
